#!/usr/bin/bash
set -x

# compile the test
CURD=$PWD
cd $CM
git checkout alg/common.hpp
git apply patch/cache-$1-nomap.patch
MODE=release make alg/prime-probe

# run the test
./alg/prime-probe --samples 20 --prefetch-cloc-addr 1 --same-target 1 --test-warm 1 > $CURD/$1.log &

# actual test used in paper
#./alg/prime-probe --samples 1000 --prefetch-cloc-addr 1 --same-target 1 --test-warm 1
