#!/usr/bin/bash
set -x

# compile the test
cd $CM
git checkout alg/common.hpp
git apply patch/cache-$1-nomap.patch
make alg/prime-probe

# run the test
./alg/prime-probe --samples 50 --prefetch-cloc-addr 1 --same-target 1 --test-warm 1

# actual test used in paper
#./alg/prime-probe --samples 1000 --prefetch-cloc-addr 1 --same-target 1 --test-warm 1
