#!/usr/bin/bash
set -x

# compile the test
CURD=$PWD
cd $CM
git checkout alg/common.hpp
git apply patch/cache-$1-nomap.patch
MODE=release make alg/ct

# run the test
./alg/ct --same-target 1 --samples 20 > $CURD/$1-ct.log &

# actual test used in paper
# ./alg/ct --same-target 1 --samples 1000
