#!/usr/bin/bash
set -x

# compile the test
CURD=$PWD
cd $CM
cp patch/common.hpp alg/common.hpp
patch alg/common.hpp patch/cache-$1-nomap.patch
touch alg/common.hpp
MODE=release make alg/ct

# run the test
./alg/ct --prefetch-target 1 --same-target 1 --samples 20 > $CURD/$1-ct-prefetch.log &

# actual test used in paper
# ./alg/ct --prefetch-target 1 --same-target 1 --samples 1000
