#!/usr/bin/bash
set -x

# compile the test
CURD=$PWD
cd $CM
git checkout alg/common.hpp
git apply patch/cache-$1-nomap.patch
MODE=release make alg/ctpp

# run the test
./alg/ctpp --same-target 1 --samples 100 | tee $CURD/$1-ctpp.log

# actual test used in paper
# ./alg/ctpp --same-target 1 --samples 1000
