./run-ct baseline
./run-ct-prefetch baseline
./run-ctpp baseline
./run-ppp baseline
./run-ct sp2021
./run-ct-prefetch sp2021
./run-ctpp sp2021
./run-ppp sp2021
./run-ct ceaser-s
./run-ct-prefetch ceaser-s
./run-ctpp ceaser-s
./run-ppp ceaser-s
./run-ct chameleon
./run-ct-prefetch chameleon
./run-ctpp chameleon
./run-ppp chameleon
./run-ct mirage-50
./run-ct-prefetch mirage-50
./run-ctpp mirage-50
./run-ppp mirage-50
./run-ct mirage-75
./run-ct-prefetch mirage-75
./run-ctpp mirage-75
./run-ppp mirage-75
./run-ct seqass
./run-ct-prefetch seqass
./run-ctpp seqass
./run-ppp seqass
