#!/usr/bin/bash
set -x

# compile spike
CURD=$PWD
cd $CM
cp patch/spike-cache.cc spike-cache.cc
patch spike-cache.cc patch/spike-$1-remap.patch
touch spike-cache.cc

cd $SPIKE/build
rm libflexicas.* spike-cache.*
make clean -C $CM
MODE=release make -j4 -C $CM
make install
