#!/usr/bin/bash
set -x

# compile the test
cd $CM
git checkout alg/common.hpp
git apply patch/cache-$1-nomap.patch
make alg/effective-cloc-acc

# run the test
./alg/effective-cloc-acc --samples 10 --same-target 1 --test-warm 1

# actual test used in paper
# ./alg/effective-cloc-acc --samples 200 --same-target 1 --test-warm 1
