#!/usr/bin/bash
set -x

# compile the test
CURD=$PWD
cd $CM
cp patch/common.hpp alg/common.hpp
patch alg/common.hpp patch/cache-$1-nomap.patch
touch alg/common.hpp
MODE=release make alg/effective-cloc-acc

# run the test
./alg/effective-cloc-acc --samples 5  > $CURD/$1.log &

# actual test used in paper
# ./alg/effective-cloc-acc --samples 200 --same-target 1 --test-warm 1
