#!/usr/bin/bash
set -x

cd $BALL_TEST/mirage/security_analysis
make clean
make -j4
cd results/base/
./run_size.sh 100
python3 get_mirage_target_spill.py
cp *_target_spill.csv $ROOT/claims/claim1/exp1/
cp *_target_spill.png $ROOT/claims/claim1/exp1/

