#!/usr/bin/bash
set -x

cd $BALL_TEST/seqass/security_analysis
make clean
CONFLICT_MAX=15 make -j4
cd results/base/
./run_size.sh 100
python3 get_seqass_target_spill.py
cp seqass_target_spill.csv $ROOT/claims/claim1/exp1/seqass_4b_target_spill.cs
cp seqass_target_spill.png $ROOT/claims/claim1/exp1/seqass_4b_target_spill.png
